from . import res_company
from . import res_config_settings
from . import mercadopublico_category
from . import mercadopublico_stage
from . import mercadopublico_buyer
from . import mercadopublico_dashboard
from . import mercadopublico_keyword
from . import mercadopublico_tender
from . import mercadopublico_tender_item
from . import crm_lead
from . import mercadopublico_api
from . import mercadopublico_location
from . import product_extension